$mainMod = SUPER

## Run wallpaper switcher
bind = SUPER, A, exec, qs -p ~/.config/quickshell-wallpaper/shell.qml # better use non Fn

## Thumbnail Bind
bind = $mainMod SHIFT, W, exec, ~/.config/hypr/scripts/build-thumbs.sh

## Run WITH matugen
bind = $mainMod SHIFT, W, exec, env WALLPICKER_MATUGEN=1 quickshell -c ~/.config/quickshell

## Run WITHOUT matugen
bind = $mainMod, W, exec, quickshell -c ~/.config/quickshell
