# Rules for Hyprland.conf

windowrule {
	name = wallpaper picker
	match:title = ^(wallpaper-picker)$
	float = on
	pin = on
	no_shadow = on
	border_color = "transparent"
    no_blur = on
	focus_on_activate = on
    center = on
 }
